

Kafka:
  Brokers: ["alikafka-serverless-cn-zqb4gbwti01-1000-vpc.alikafka.aliyuncs.com:9092","alikafka-serverless-cn-zqb4gbwti01-2000-vpc.alikafka.aliyuncs.com:9092","alikafka-serverless-cn-zqb4gbwti01-3000-vpc.alikafka.aliyuncs.com:9092"]
  ClientId: ""
  UserName: ""
  Password: ""
  NeedAuth: false

Rules:
  - EmqxTopicPrefix: "device/[^/]+/message/up/ivs_result"
    KafkaTopic: "device_message_up_ivs_result"