

Kafka:
  Brokers: ["alikafka-serverless-cn-zqb4gbwti01-1000-vpc.alikafka.aliyuncs.com:9092","alikafka-serverless-cn-zqb4gbwti01-2000-vpc.alikafka.aliyuncs.com:9092","alikafka-serverless-cn-zqb4gbwti01-3000-vpc.alikafka.aliyuncs.com:9092"]
  NeedAuth: false

Rules:
  - EmqxTopicPrefix: "111"
    KafkaTopic: "222"
